### ISSUE TITLE
always loading the same comments.

### ISSUE THREAD

**Issue by samvloeberghs** [Useful-Software-Solutions-Ltd/angular2-disqus#3]
Hi,
I'm using your plugin here ( on both pages ) but it loads the same comments everywhere:

https://samvloeberghs.be/posts/whats-with-the-subjects-in-rxjs5
https://samvloeberghs.be/posts/scroll-to-top-on-angular2-router-navigation

Any idea?

Kind regards
Sam V.

**Comment by JayChase** [comment]
It looks like something has changed on the DISQUS side with regards to needing both the page id and url. It used to work well with just the id. Now it seems that if the first post is made with the url and the id then it will be ok but if the id does not already exist then DISQUS will just start putting everything on a single thread. I will need to do a bit of refactoring to make sure DISQUS.reset is never called without both a url and id value. I'll try to get something into beta over the next couple of days.

**Comment by JayChase** [comment]
This should be fixed in the latest release. Let me know if you have any further problems.

**Comment by samvloeberghs** [comment]
Hi @JayChase checking it asap! thanks for your effort!!!

**Comment by samvloeberghs** [comment]
Hi @JayChase 

I'ved updated to 5.0.0, but I'm still seeing the same comments on different pages of my web app.
I'm pretty sure the identifier is correct & the page urls are 2 different uniques ..

https://samvloeberghs.be/posts/whats-with-the-subjects-in-rxjs5
https://samvloeberghs.be/posts/scroll-to-top-on-angular2-router-navigation

Any suggestions?
Kind regards
Sam V.

**Comment by JayChase** [comment]
Hi. Sorry it has been a while. did you have any luck with this? If not I should have some time next week to take a look.

**Comment by FabienGreard** [comment]
Hey Jay, 
Hope you're doing good.
I'm having the same issue, did you manage to find something yet ? 
(i have checked that the identifier is unique, same for the urls)
